name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: 'Docker CI'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup docker builder
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          for DIR in $(find . -type f -name 'Dockerfile' | sed -r 's|/[^/]+$||' |sort |uniq)
          do
            docker build $DIR \
              --no-cache
          done
