name: Debezium Strimzi

on:
  push:
    branches:
      - main
    paths:
      - 'debezium/strimzi/**'

jobs:
  build:
    name: Build Debezium Strimzi
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        strimzi: [ "0.28.0-kafka-3.1.0", "0.29.0-kafka-3.1.1" ]
        debezium: [ "1.9.4.Final" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ./debezium/strimzi
          push: true
          tags: loustler/debezium-strimzi:${{ matrix.strimzi }}_${{ matrix.debezium }}
          tag_with_ref: true
          build-args: |
            VERSION=${{ matrix.strimzi }}
            DEBEZIUM_VERSION=${{ matrix.debezium }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
