name: Jekyll

on:
  push:
    branches:
      - master
    tags:
      - 'ruby-*'
    paths:
      - 'jekyll/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      ‐ name: build-push
        uses: docker/build-push-action@v1
        env:
          INPUT_DOCKERFILE: jekyll/
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: loustler/jekyll
          repository: loustler/dockerfile
          tag_with_ref: true