name: Jekyll

on:
  push:
    tags:
      - 'jekyll-*'
    paths:
      - 'jekyll/**'

jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get docker image tag
        id: get_docker_image_tag
        env:
          ORIGIN_TAG: ${{ steps.get_version.outputs.version }}
        run: |
          tag_=${ORIGIN_TAG#"airflow-"}

          echo "::set-output name=tag::$tag_"
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ./jekyll
          push: true
          tags: |
            loustler/jekyll:latest
            loustler/jekyll:${{ steps.get_docker_image_tag.outputs.tag }}
          tag_with_ref: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
